name: Android Emulator Tests with Internet

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    - name: Create AVD with internet support
      run: |
        echo "y" | sdkmanager "system-images;android-33;google_apis;x86_64"
        echo "no" | avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64" -c 1000M -f

    - name: Start emulator with internet config
      run: |
        emulator -avd test -no-window -no-boot-anim -no-audio -gpu swiftshader_indirect -dns-server 8.8.8.8 &
        adb wait-for-device
        # Wait for full boot
        while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do sleep 2; done
        # Verify internet
        adb shell ping -c 1 8.8.8.8

    - name: Run tests (example)
      run: |
        ./gradlew connectedCheck

    - name: Stop emulator
      if: always()
      run: |
        adb emu kill
